name: rewiverb4000s
description: An EWI 4000s Patch Editor in flutter

publish_to: 'none'
version: 0.0.1

environment:
  sdk: ">=2.17.0-222.0.dev <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_midi_command:
    git: https://github.com/Kibibibit/FlutterMidiCommand.git
  geoff:
    git: https://github.com/Kibibibit/geoff.git

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true